package dialects

import (
	"strings"
	"testing"
)

func TestOracleCreateTable(t *testing.T) {
	o := NewOracle()
	sql := o.CreateTable("goose_db_version")
	for _, want := range []string{
		"CREATE TABLE goose_db_version",
		"GENERATED BY DEFAULT AS IDENTITY",
		"NUMBER(19)",
		"NUMBER(1)",
		"TIMESTAMP",
		"PRIMARY KEY",
	} {
		if !strings.Contains(sql, want) {
			t.Errorf("CreateTable missing %q", want)
		}
	}
}

func TestOracleInsertVersion(t *testing.T) {
	o := NewOracle()
	sql := o.InsertVersion("goose_db_version")
	if !strings.Contains(sql, ":1") || !strings.Contains(sql, ":2") {
		t.Error("InsertVersion should use Oracle positional parameters :1, :2")
	}
	if !strings.Contains(sql, "INSERT INTO goose_db_version") {
		t.Error("InsertVersion should reference the table name")
	}
}

func TestOracleDeleteVersion(t *testing.T) {
	o := NewOracle()
	sql := o.DeleteVersion("goose_db_version")
	if !strings.Contains(sql, "DELETE FROM goose_db_version") {
		t.Error("DeleteVersion should reference the table name")
	}
	if !strings.Contains(sql, ":1") {
		t.Error("DeleteVersion should use Oracle positional parameter :1")
	}
}

func TestOracleGetMigrationByVersion(t *testing.T) {
	o := NewOracle()
	sql := o.GetMigrationByVersion("goose_db_version")
	if !strings.Contains(sql, "FETCH FIRST 1 ROWS ONLY") {
		t.Error("GetMigrationByVersion should use FETCH FIRST (Oracle 12c+ syntax)")
	}
	if !strings.Contains(sql, ":1") {
		t.Error("GetMigrationByVersion should use Oracle positional parameter :1")
	}
}

func TestOracleListMigrations(t *testing.T) {
	o := NewOracle()
	sql := o.ListMigrations("goose_db_version")
	if !strings.Contains(sql, "ORDER BY id DESC") {
		t.Error("ListMigrations should order by id descending")
	}
}

func TestOracleGetLatestVersion(t *testing.T) {
	o := NewOracle()
	sql := o.GetLatestVersion("goose_db_version")
	if !strings.Contains(sql, "MAX(version_id)") {
		t.Error("GetLatestVersion should use MAX(version_id)")
	}
}

func TestOracleTableExists(t *testing.T) {
	o := NewOracle()

	t.Run("simple table", func(t *testing.T) {
		sql := o.TableExists("goose_db_version")
		if !strings.Contains(sql, "user_tables") {
			t.Error("simple table should query user_tables")
		}
		if !strings.Contains(sql, "GOOSE_DB_VERSION") {
			t.Error("table name should be uppercased")
		}
	})

	t.Run("schema-qualified table", func(t *testing.T) {
		sql := o.TableExists("myschema.goose_db_version")
		if !strings.Contains(sql, "all_tables") {
			t.Error("schema-qualified table should query all_tables")
		}
		if !strings.Contains(sql, "MYSCHEMA") {
			t.Error("schema name should be uppercased")
		}
		if !strings.Contains(sql, "GOOSE_DB_VERSION") {
			t.Error("table name should be uppercased")
		}
	})

	t.Run("invalid identifier rejected", func(t *testing.T) {
		sql := o.TableExists("'; DROP TABLE users; --")
		if sql != "" {
			t.Error("invalid identifier should return empty string")
		}
	})

	t.Run("invalid schema rejected", func(t *testing.T) {
		sql := o.TableExists("bad'; --.table")
		if sql != "" {
			t.Error("invalid schema should return empty string")
		}
	})
}

func TestParseOracleTableIdentifier(t *testing.T) {
	tests := []struct {
		input      string
		wantSchema string
		wantTable  string
	}{
		{"goose_db_version", "", "goose_db_version"},
		{"myschema.goose_db_version", "myschema", "goose_db_version"},
		{"MYSCHEMA.GOOSE_DB_VERSION", "MYSCHEMA", "GOOSE_DB_VERSION"},
		{"a.b.c", "a", "b.c"},
	}
	for _, tt := range tests {
		t.Run(tt.input, func(t *testing.T) {
			schema, table := parseOracleTableIdentifier(tt.input)
			if schema != tt.wantSchema {
				t.Errorf("schema: got %q, want %q", schema, tt.wantSchema)
			}
			if table != tt.wantTable {
				t.Errorf("table: got %q, want %q", table, tt.wantTable)
			}
		})
	}
}
