-- +goose Up
CREATE TABLE owners (
    owner_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    owner_name VARCHAR2(255) NOT NULL,
    owner_type VARCHAR2(20) NOT NULL CHECK (owner_type IN ('user', 'organization'))
);

CREATE TABLE repos (
    repo_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    repo_full_name VARCHAR2(255) NOT NULL,
    repo_owner_id NUMBER NOT NULL REFERENCES owners(owner_id) ON DELETE CASCADE
);

-- +goose Down
DROP TABLE repos;
DROP TABLE owners;
